# 监听IP，默认127.0.0.1，可修改
IP=127.0.0.1

# 启动端口，默认5000，可修改
PORT=5000

# 身份证书，仅支持cer格式
ssl_certfile=etc/ssl/server.cer

# 私钥文件，仅支持pem格式
ssl_keyfile=etc/ssl/server_key.pem

# 私钥文件密码
ssl_keyfile_password=etc/ssl/cert_pwd

# 信任证书，仅支持cer格式
ssl_ca_certs=etc/ssl/trust.cer

# 吊销列表
#ssl_crl_file=etc/ssl/revocationlist.crl

# 校验对端证书
verify_client=true
